Error handling in provider grpc (#1677)
Presently, if an error is raised either in Pulumi's code or in user's
code of provider implementation, the client would receive a generate
gRPC INTERNAL error with no error message or stack trace. This is very
unhelpful for provider/component authors, since they have to guess what
went wrong for each error.

This PR introduces an ErrorHandlingInterceptor and wires it into all
gRPC methods that we have in the provider service. It will relay any
exception thrown either from our code or from user's implementation and
return its details over gRPC.

An example of UX after the change for a user error:

```
    Error: error resolving type of resource hello: internal error loading package "javap": Error loading schema from plugin: rpc error: code = Internal desc = java.lang.RuntimeException: Could not find schema.json in package
    java.lang.RuntimeException: Could not find schema.json in package
    	at com.pulumi.example.provider.ExampleProvider.getSchema(ExampleProvider.java:21)
    	at com.pulumi.provider.internal.ResourceProviderService$ResourceProviderImpl.getSchema(ResourceProviderService.java:118)
    	at pulumirpc.ResourceProviderGrpc$MethodHandlers.invoke(ResourceProviderGrpc.java:2179)
    	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
    	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
    	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
    	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
    	at com.pulumi.provider.internal.ErrorHandlingInterceptor$1.onHalfClose(ErrorHandlingInterceptor.java:19)
    	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:356)
    	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:829)
      on Pulumi.yaml line 9:
       9:     type: javap:index:HelloWorld
```


An example for a system error:

```
    error: javap:index:HelloWorld resource 'hello2' has a problem: java.lang.IllegalStateException: Deployment#instance should only be set once at the beginning of a 'run' call.
    java.lang.IllegalStateException: Deployment#instance should only be set once at the beginning of a 'run' call.
    	at com.pulumi.deployment.internal.DeploymentInstanceHolder.setInstance(DeploymentInstanceHolder.java:39)
    	at com.pulumi.deployment.internal.DeploymentImpl.fromInline(DeploymentImpl.java:172)
    	at com.pulumi.internal.PulumiInternal.fromInline(PulumiInternal.java:68)
    	at com.pulumi.provider.internal.ResourceProviderService$ResourceProviderImpl.construct(ResourceProviderService.java:199)
    	at pulumirpc.ResourceProviderGrpc$MethodHandlers.invoke(ResourceProviderGrpc.java:2231)
    	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
    	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
    	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
    	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
    	at com.pulumi.provider.internal.ErrorHandlingInterceptor$1.onHalfClose(ErrorHandlingInterceptor.java:19)
    	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:356)
    	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:829)
    error: javap:index:HelloWorld resource 'hello' has a problem: grpc: the client connection is closing
```