build(deps): bump nl.jqno.equalsverifier:equalsverifier from 3.15.1 to 3.18 in /sdk/java (#1519)
Bumps
[nl.jqno.equalsverifier:equalsverifier](https://github.com/jqno/equalsverifier)
from 3.15.1 to 3.18.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/jqno/equalsverifier/releases">nl.jqno.equalsverifier:equalsverifier's
releases</a>.</em></p>
<blockquote>
<h2>Release equalsverifier-3.18</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.17.5</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.17.4</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.17.3</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.17.2</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.17.1</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.17</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.16.2</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.16.1</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.16</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.15.8</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.15.7</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.15.6</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.15.5</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.15.4</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.15.3</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
<h2>Release equalsverifier-3.15.2</h2>
<p>For a list of changes in this version, see <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">CHANGELOG.md</a>.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/jqno/equalsverifier/blob/main/CHANGELOG.md">nl.jqno.equalsverifier:equalsverifier's
changelog</a>.</em></p>
<blockquote>
<h2>[3.18] - 2024-12-24</h2>
<h3>Added</h3>
<ul>
<li>Tools like IntelliJ, Spotbugs and ErrorProne now report when you
forget to call <code>.verify()</code> at the end of an EqualsVerifier
invocation (through the <code>@CheckReturnValue</code> annotation).</li>
<li>Adds prefab values for Java 21's <code>SequencedCollection</code>,
<code>SequencedSet</code> and <code>SequencedMap</code>.</li>
</ul>
<h2>[3.17.5] - 2024-12-06</h2>
<h3>Fixed</h3>
<ul>
<li>SpotBugs-annotations dependency is suddenly needed in builds that do
certain kinds of annotation processing. (<a
href="https://redirect.github.com/jqno/equalsverifier/issues/1026">Issue
1026</a>)</li>
<li>Significant fields error when testing a class with a field that has
a Map with an array as its value type. (<a
href="https://redirect.github.com/jqno/equalsverifier/issues/1027">Issue
1027</a>)</li>
</ul>
<h3>Changed</h3>
<ul>
<li>Reverted the refactorings introduced in versions 3.17.2, 3.17.3 and
3.17.4, as they were causing more problems than they were solving. See
<a href="https://jqno.nl/post/2024/12/06/unrefactoring/">this blog
post</a> for some background.</li>
</ul>
<h2>[3.17.4] - 2024-11-29</h2>
<h3>Fixed</h3>
<ul>
<li>Fixes bug where the wrong generic type was provided when multiple
fields of the same type but with different generic parameters exist. (<a
href="https://redirect.github.com/jqno/equalsverifier/issues/1022">Issue
1022</a>)</li>
</ul>
<h3>Changed</h3>
<ul>
<li>The internal instantiation logic has been further refactored, to be
more robust and extensible for future enhancements.</li>
</ul>
<h2>[3.17.3] - 2024-11-07</h2>
<h3>Fixed</h3>
<ul>
<li>Fixes bug when passing a subclass of a field's type into
<code>#withPrefabValues()</code> (which was introduced in the previous
version). (<a
href="https://redirect.github.com/jqno/equalsverifier/issues/1014">Issue
1014</a>)</li>
<li>In Windows builds, the handling of line endings didn't work
properly. (<a
href="https://redirect.github.com/jqno/equalsverifier/issues/1015">Issue
1015</a>)</li>
</ul>
<h2>[3.17.2] - 2024-11-05</h2>
<h3>Fixed</h3>
<ul>
<li>It's now possible to pass a subclass of a field's type into
<code>#withPrefabValuesForField()</code>. (<a
href="https://redirect.github.com/jqno/equalsverifier/issues/1012">Issue
1012</a>)</li>
</ul>
<h3>Changed</h3>
<ul>
<li>The internal instantiation logic has been further refactored, to be
more robust and extensible for future enhancements.</li>
</ul>
<h2>[3.17.1] - 2024-10-02</h2>
<h3>Fixed</h3>
<ul>
<li>Instantiates <code>java.sql.Date</code> only when available, so
EqualsVerifier no longer throws <code>NoClassDefFoundError</code> when
it's not available (for instance, when running EqualsVerifier standalone
instead of as part of a test suite). (<a
href="https://redirect.github.com/jqno/equalsverifier/issues/746">Issue
746</a>)</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/jqno/equalsverifier/commit/b5bdc51c6b37d14375ec22ec68adb3bfaa056087"><code>b5bdc51</code></a>
Bumps version to 3.18</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/7f45b62df48d8083242833017a4d069e30e99a02"><code>7f45b62</code></a>
Switches JReleaser from Sonatype/Maven OSSRH to Central Portal</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/5ef9c6f4dd401a76b6b95e85d43afd89839823f3"><code>5ef9c6f</code></a>
Updates CHANGELOG for release</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/38f1e281b2fc0ce447fb970af59f61b294f35393"><code>38f1e28</code></a>
Runs several OpenRewrite recipes</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/6c50c0a7e18ecd4a21e04adb893287638082848f"><code>6c50c0a</code></a>
Merge pull request <a
href="https://redirect.github.com/jqno/equalsverifier/issues/1032">#1032</a>
from jqno/dependabot/maven/dependencies-f8ef0a761a</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/005edb33060ee1dcca86f73d4f90b6364ddf90bb"><code>005edb3</code></a>
Bump the dependencies group with 4 updates</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/27385a51ac743222990ac6823e6836df7fa7b8e4"><code>27385a5</code></a>
Replaces assertAll with assertThat().satisfies</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/77ebac810977b7dc05de13bb1d1e075e440fb27d"><code>77ebac8</code></a>
Merge pull request <a
href="https://redirect.github.com/jqno/equalsverifier/issues/1031">#1031</a>
from timtebeek/assertj-best-practices</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/6004455b1c1db171cf1996a50ae5f8c3343663c7"><code>6004455</code></a>
Apply AssertJ best practices</li>
<li><a
href="https://github.com/jqno/equalsverifier/commit/5a8f5d817e85a448b283f02c59e45d5d100f1ea4"><code>5a8f5d8</code></a>
Merge branch 'assertj'</li>
<li>Additional commits viewable in <a
href="https://github.com/jqno/equalsverifier/compare/equalsverifier-3.15.1...equalsverifier-3.18">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=nl.jqno.equalsverifier:equalsverifier&package-manager=gradle&previous-version=3.15.1&new-version=3.18)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>