Back out the Java changes
It appears that they cause build failures:

```
/home/runner/work/pulumi-java/pulumi-java/sdk/java/pulumi/src/test/java/com/pulumi/provider/internal/ResourceProviderServiceTest.java:9: error: package io.grpc.inprocess does not exist

import io.grpc.inprocess.InProcessChannelBuilder;
                        ^
/home/runner/work/pulumi-java/pulumi-java/sdk/java/pulumi/src/test/java/com/pulumi/provider/internal/
```