Fix example test `minimal`
This commit fixes the broken minimal example due to version mismatch.

For context, the error message was as follows:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< com.pulumi.example:minimal >---------------------
[INFO] Building minimal 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.1.0:enforce (enforce) @ minimal ---
[WARNING]
        Dependency convergence error for com.google.errorprone:error_prone_annotations:jar:2.14.0:compile paths to dependency are:
        +-com.pulumi.example:minimal:jar:1.0-SNAPSHOT
          +-io.grpc:grpc-okhttp:jar:1.52.1:compile
            +-io.grpc:grpc-core:jar:1.52.1:compile
              +-io.grpc:grpc-api:jar:1.52.1:compile
                +-com.google.errorprone:error_prone_annotations:jar:2.14.0:compile
        and
        +-com.pulumi.example:minimal:jar:1.0-SNAPSHOT
          +-io.grpc:grpc-okhttp:jar:1.52.1:compile
            +-io.grpc:grpc-core:jar:1.52.1:compile
              +-com.google.errorprone:error_prone_annotations:jar:2.14.0:compile
        and
        +-com.pulumi.example:minimal:jar:1.0-SNAPSHOT
          +-com.pulumi:pulumi:jar:0.9.1-alpha.1681151802+6162c34c:compile
            +-io.grpc:grpc-stub:jar:1.54.0:runtime
              +-com.google.errorprone:error_prone_annotations:jar:2.18.0:runtime

[WARNING]
        Dependency convergence error for io.grpc:grpc-api:jar:1.52.1:compile paths to dependency are:
        +-com.pulumi.example:minimal:jar:1.0-SNAPSHOT
          +-io.grpc:grpc-okhttp:jar:1.52.1:compile
            +-io.grpc:grpc-core:jar:1.52.1:compile
              +-io.grpc:grpc-api:jar:1.52.1:compile
        and
        +-com.pulumi.example:minimal:jar:1.0-SNAPSHOT
          +-com.pulumi:pulumi:jar:0.9.1-alpha.1681151802+6162c34c:compile
            +-io.grpc:grpc-protobuf:jar:1.54.0:runtime
              +-io.grpc:grpc-api:jar:1.54.0:runtime
        and
        +-com.pulumi.example:minimal:jar:1.0-SNAPSHOT
          +-com.pulumi:pulumi:jar:0.9.1-alpha.1681151802+6162c34c:compile
            +-io.grpc:grpc-protobuf:jar:1.54.0:runtime
              +-io.grpc:grpc-protobuf-lite:jar:1.54.0:runtime
                +-io.grpc:grpc-api:jar:1.54.0:runtime
        and
        +-com.pulumi.example:minimal:jar:1.0-SNAPSHOT
          +-com.pulumi:pulumi:jar:0.9.1-alpha.1681151802+6162c34c:compile
            +-io.grpc:grpc-stub:jar:1.54.0:runtime
              +-io.grpc:grpc-api:jar:1.54.0:runtime

[ERROR] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
        Failed while enforcing releasability. See above detailed error message.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.491 s
[INFO] Finished at: 2023-04-10T19:43:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.1.0:enforce (enforce) on project minimal: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

    program.go:738:
        	Error Trace:	/home/runner/work/pulumi-java/pulumi-java/tests/examples/program.go:738
        	            				/home/runner/work/pulumi-java/pulumi-java/tests/examples/java_examples_test.go:165
        	Error:      	Received unexpected error:
        	            	copying test to temp dir : Failed to prepare /tmp/p-it-fv-az203-5-minimal-e46eccc4-2865352920: exit status 1
        	Test:       	TestExamples/minimal
--- FAIL: TestExamples (0.00s)
--- FAIL: TestExamples/minimal (11.84s)
```